### ISSUE TITLE
implement a method to list shard states

### ISSUE THREAD

**Issue by raulk** [filecoin-project/dagstore#29]
Implement a getter:

```go
type DAGStore interface {
    AllShardStates() map[shard.Key]ShardState
}
```

**Comment by aarshkshah1992** [comment]
@raulk Why is this a must-have for 0.1 ? We can probably get this in post-M1.

**Comment by raulk** [comment]
v0.1 needs to be production-ready, and production-ready software must be observable. Draft implementation in #40.
