### ISSUE TITLE
implement shard failure management and recovery

### ISSUE THREAD

**Issue by raulk** [filecoin-project/dagstore#33]
Shards can fail due for various reasons:

1. mount is inaccessible
2. index failed to populate
3. internal incongruency
4. released with error

When a shard fails, the application must be notified and given the chance to recover.

## Implementation

1. Implement `RecoverShard(ctx context.Context, key shard.Key, out chan ShardResult) error`, which resets the state of the shard, removes its index, and re-registers it from scratch.
2. Accept an `ErrorCh chan ShardError` option in the constructor, which if not-nil will be notified of shard errors.

**Comment by aarshkshah1992** [comment]
@raulk Why is this a must-have for 0.1 ? We can probably get this in post M1. For now, we can simply get the clients (the Filecoin storage Market and retrieval Markets) to retry things on detecting errors.
