### ISSUE TITLE
lazy indexing

### ISSUE THREAD

**Issue by raulk** [filecoin-project/dagstore#45]
Migrating existing lotus deals to the DAG store currently entails having to unseal every deal to eagerly index it. This is prohibitive. We need to add support for lazy indexing, specifically for the migration, but also for other use cases down the road.

- [ ] Add a `LazyIndexing` option to `RegisterOpts` that disables indexing on registration.
    - We'll enable this when we register shards for deals that the storage subsystem has no unsealed CAR for.
- [ ] Add logic to index an unindexed shard when it's first acquired.
- [ ] Unit tests.

**Comment by aarshkshah1992** [comment]
@raulk After thinking this through and discussing this with @dirkmc , we've decided to skip the upfront migration and instead Register shards for all **_pre-existing_** deals when they are first retrieved. **_For new deals, we'll of-course register the shard/index it when the storage deal is made._** Rationale:

- The one time migration can get messy. We can't force miners to Unseal deals for which they don't have an Unsealed copy. So, we'd have to Register Shards only for already unsealed deals and punt the Indexing for the sealed deals when we retrieve them. If we're anyways doing this,  why not Index all pre-existing deals during retrieval ?
- If we have to actually unseal a pre-existing deal during retrieval, the time taken by the unsealing dwarfs the time that'll be taken by the Indexing. 
- If we  already have an unsealed copy for a pre-existing deal, we pay the Indexing cost **_only_** during the first retrieval. 
- In return for this tradeoff, we get rid of a messy migration process where we'd have to answer questions like:
  - Do we ship a separate utility for the migration or do we do it when the Miner starts up ? 
  - If it's a separate utility,  what if miners don't run it ?
  - If we do it when the Miner starts up, what if a registration fails ? How do we recover ? Are miners okay waiting for startup to complete till we finish indexing all their pre-existing Unsealed deals ?
- We also get rid of having to introduce this "lazy Indexing" feature in the DAG Store.
- Given the tight deadline on M1 and considering all of the above, the value of the upfront migration is extremely questionable.

**Comment by raulk** [comment]
I'm confused by the comment because the problems you list are the problems that lazy registration solves, yet you dismiss the solution.

Feel free to experiment with the suggested approach, but it's not ultimately what we want.

The proposed solution has one major flaw. It entails keeping additional state in markets code forever to track which shard have been registered, and which haven't. Unless you intend to rely on an ErrShardNotFound error to register the shard, which is a hack.

Architecturally speaking, this solution stretches out the migration operation that is supposed to be a clean, one-off, to _infinity_, by turning it into a permanent code path, i.e. it creates technical debt.

It also creates much more complexity. A system where each  deal known to the miner is a shard is much easier to reason about, debug, and introspect, than a system where some deals are shards and others aren't.

The lazy registration solution achieves the required behaviour, without shifting complexity to where it doesn't belong, and in a way that it can be reused by other  consumers down the road like IPFS.

---

PS. Please don't close issues until the author has agreed with your assessment!

**Comment by raulk** [comment]
The migration process is very simple. It consists of enumerating all deals and registering lazy shards for them. Then we record a flag in the metadata store. After all the network has upgraded and is running the DAG store, we eliminate that code path, or put it behind a command. Why do we need a separate utility?

**Comment by raulk** [comment]
Re: the deadline comment, I think you're overestimating the effort this needs. Let's assess what leads you to the conclusion that the markets-side hack is less effort than doing things right.

**Comment by raulk** [comment]
Just to recap, the migration is as simple as registering all existing deals as lazy shards. This would index existing deals only when they're accessed for the first time.

We can also add an operation to force indexing of a shard, so we could trigger the indexing of unsealed deals as a background process, staggering them in time.

This way the migration is very lightweight and non-blocking, and the indexing of past deals is performed gradually in the background.
